name: CI/CD Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v4

      - name: Verificar arquivos (debug)
        run: |
          ls -la
          ls -la docker-compose.yml
          ls -la infra/Dockerfile

      - name: Copiar projeto para VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 72.61.27.84
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "."
          target: "/var/www/projetos/finance/Finance-frontend"
          strip_components: 0

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 72.61.27.84
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /var/www/projetos/finance/Finance-frontend
            docker compose down
            docker compose up -d --build